name: Cypress Tests

on:
  push:
    branches: [main, cypress-workflow]
  pull_request:
    branches: [main, cypress-workflow]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache do Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}

      - name: Criar package.json mínimo
        run: |
          echo '{}' > package.json

      - name: Instalar Cypress
        run: npm install cypress --save-dev
        env:
          CYPRESS_VERIFY_TIMEOUT: 100000

      - name: Rodar Cypress
        run: npx cypress run
        env:
          CYPRESS_VERIFY_TIMEOUT: 100000

      - name: Salvar vídeos e screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

