name: Cypress Tests

on:
  push:
    branches: [main, cypress-workflow]
  pull_request:
    branches: [main, cypress-workflow]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Cypress
        run: npm install cypress --save-dev

      - name: Rodar Cypress
        run: npx cypress run

      - name: Salvar vídeos e screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

